name: Sync Upstream

on:
  schedule:
    - cron: '0 2 * * *'  # Every day at 2 AM UTC
  workflow_dispatch:

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    env:
      DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}

    steps:
      - name: Checkout your fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Add upstream and fetch tags
        run: |
          git remote add upstream https://github.com/olirice/alembic_utils.git
          git fetch upstream $DEFAULT_BRANCH

      - name: Merge upstream into your fork
        run: |
          git checkout $DEFAULT_BRANCH
          git merge upstream/$DEFAULT_BRANCH --no-edit 

      - name: Push updated main and new tags to origin
        run: |
          git push origin $DEFAULT_BRANCH

      - name: Push only missing tags to origin
        run: |
          for tag in $(git tag); do
            if ! git ls-remote --tags origin "refs/tags/$tag" | grep -q "refs/tags/$tag"; then
              echo "Tag $tag not found on origin. Pushing..."
              git push origin refs/tags/$tag
            else
              echo "Tag $tag already exists on origin. Skipping."
            fi
          done
